ERROR 2025-03-17 17:24:10,381 views User does not exist
ERROR 2025-03-17 17:26:20,694 views Invalid Credentials
ERROR 2025-03-19 16:18:02,002 log Internal Server Error: /api/clients/5/activate-client/
Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2025-03-19 16:53:34,018 log Internal Server Error: /api/clients/4/contracts/6/events/6/assign-support/
Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'CustomUsers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicevents\event\views.py", line 149, in assign_support_member
    support_contact = CustomUsers.objects.get(id=support_contact_id, role="Support")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 369, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <CustomUsers: salesmember_2>.
ERROR 2025-03-19 16:55:19,950 log Internal Server Error: /api/clients/4/contracts/6/events/6/assign-support/
Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'CustomUsers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicevents\event\views.py", line 149, in assign_support_member
    support_contact = CustomUsers.objects.get(id=support_contact_id, role="Support")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 369, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <CustomUsers: salesmember_2>.
ERROR 2025-03-19 16:56:24,239 log Internal Server Error: /api/clients/4/contracts/6/events/6/assign-support/
Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'CustomUsers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicevents\event\views.py", line 149, in assign_support_member
    support_contact = CustomUsers.objects.get(id=support_contact_id, role="Support")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 369, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <CustomUsers: salesmember_1>.
ERROR 2025-03-19 16:56:51,083 log Internal Server Error: /api/clients/4/contracts/6/events/6/assign-support/
Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'CustomUsers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicevents\event\views.py", line 149, in assign_support_member
    support_contact = CustomUsers.objects.get(id=support_contact_id, role="Support")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 369, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <CustomUsers: supportmember_1>.
ERROR 2025-03-19 16:57:28,305 log Internal Server Error: /api/clients/4/contracts/6/events/6/assign-support/
Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'CustomUsers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicevents\event\views.py", line 149, in assign_support_member
    support_contact = CustomUsers.objects.get(id=support_contact_id, role="Support")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 369, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <CustomUsers: salesmember_2>.
ERROR 2025-03-19 16:58:23,930 log Internal Server Error: /api/clients/4/contracts/6/events/6/assign-support/
Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'CustomUsers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicevents\event\views.py", line 149, in assign_support_member
    support_contact = CustomUsers.objects.get(id=support_contact_id, role__name="Support")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 369, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <CustomUsers: salesmember_2>.
ERROR 2025-03-19 17:00:56,889 log Internal Server Error: /api/clients/4/contracts/6/events/6/assign-support/
Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicevents\event\views.py", line 149, in assign_support_member
    support_contact = CustomUsers.objects.get(id=support_contact_id, role__name="Support")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1379, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1423, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'name' for ForeignKey or join on the field not permitted.
ERROR 2025-03-19 17:01:41,842 log Internal Server Error: /api/clients/4/contracts/6/events/6/assign-support/
Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicevents\event\views.py", line 149, in assign_support_member
    support_contact = CustomUsers.objects.get(id=support_contact_id, role__name="Support")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1379, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\sql\query.py", line 1423, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'name' for ForeignKey or join on the field not permitted.
ERROR 2025-03-19 17:06:19,377 log Internal Server Error: /api/clients/4/contracts/6/events/6/assign-support/
Traceback (most recent call last):
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicevents\event\views.py", line 151, in assign_support_member
    event_obj.support_contact = support_contact.id
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.panchal\Documents\Openclassrooms\OC_Project_12_EPIC_BackEnd\epicenv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 287, in __set__
    raise ValueError(
ValueError: Cannot assign "5": "Event.support_contact" must be a "CustomUsers" instance.
